# Generated by Django 4.1.3 on 2023-04-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_delete_login_alter_employee_ecompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cLogo',
        ),
    ]
